# Generated by Django 5.1.1 on 2026-04-18 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '1056_customfieldinstance_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('htr_correction', 'HTR correction'), ('search_click', 'Search result click'), ('search_rating', 'Search rating')], max_length=32)),
                ('correction_text', models.TextField(blank=True, default='')),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_feedback', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'kind'], name='ml_hooks_fe_documen_a02701_idx'), models.Index(fields=['created_at'], name='ml_hooks_fe_created_1bfc25_idx')],
            },
        ),
    ]
