services:
  fastapi_server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.fastapi
      args:
        # Chameleon P100
        BASE_IMAGE: nvidia/cuda:11.8.0-runtime-ubuntu22.04
        TORCH_INDEX: https://download.pytorch.org/whl/cu118

    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TORCH_CUDA_ARCH_LIST=6.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
